version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: gotcha_mysql
    ports:
      - 3406:3306
    volumes:
      - ~/.indetail/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=indetail
      - MYSQL_ROOT_PASSWORD=root

